export { Hero } from './Hero'
export { HeroVisual } from './HeroVisual'
export { Stats } from './Stats'
export { Services } from './Services'
export { Workflow } from './Workflow'
export { Industries } from './Industries'
export { CaseStudies } from './CaseStudies'
export { Process } from './Process'
